{% set name = "dask-ms" %}
{% set version = "0.2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d3b3052b886afdbe5f06017d0f7010a4593fe0b8c1711b7063523d083ee2d8d7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core >=1.0
  run:
    - appdirs
    - donfig
    - python >=3.8
    - dask >=2.2.0
    - numpy >=1.14.0
    - python-casacore >=3.3.1
    - s3fs
    - pyarrow >=3.0.0
    - zarr >=2.6.1
    - xarray >0.12.0

test:
  imports:
    - daskms
  commands:
    - ${PYTHON} -c "from daskms import xds_from_ms"
    - ${PYTHON} -c "from daskms import xds_from_table"
    - ${PYTHON} -c "from daskms import xds_to_table"
    - ${PYTHON} -c "from daskms import TableProxy"

about:
  home: https://github.com/ska-sa/dask-ms
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Implementation of a dask/xarray dataset backed by a CASA MS

extra:
  recipe-maintainers:
    - sebastian-luna-valero
    - JSKenyon
    - sjperkins
