{% set name = "dask-ms" %}
{% set version = "0.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7c2fe4c0ed63a06c2b777065e5f90b55db520cfa348293e6504832c907375b60

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dask >=2.2.0
    - numpy >=1.14.0
    - python-casacore >=3.3.1
    - xarray >0.12.0

test:
  imports:
    - daskms
  commands:
    - ${PYTHON} -c "from daskms import xds_from_ms"
    - ${PYTHON} -c "from daskms import xds_from_table"
    - ${PYTHON} -c "from daskms import xds_to_table"
    - ${PYTHON} -c "from daskms import TableProxy"

about:
  home: https://github.com/ska-sa/dask-ms
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Implementation of a dask/xarray dataset backed by a CASA MS

extra:
  recipe-maintainers:
    - sebastian-luna-valero
    - JSKenyon
    - sjperkins
