{% set name = "dask-ms" %}
{% set version = "0.2.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ab97b0132a7290cc05c3b41db8833f7933e30df56d42a38d27631762b4988580

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0
  run:
    - appdirs
    - donfig
    - python >={{ python_min }}
    - dask >=2024.1.0,<2024.11.0
    - numpy >=2.0.0
    - python-casacore >=3.6.1
    - s3fs >=2024.1.0
    - pyarrow >=16.1.0
    - zarr >=2.17.0
    - xarray >2024.1.0

test:
  imports:
    - daskms
  commands:
    - ${PYTHON} -c "from daskms import xds_from_ms"
    - ${PYTHON} -c "from daskms import xds_from_table"
    - ${PYTHON} -c "from daskms import xds_to_table"
    - ${PYTHON} -c "from daskms import TableProxy"
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/ska-sa/dask-ms
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Implementation of a dask/xarray dataset backed by a CASA MS

extra:
  recipe-maintainers:
    - sebastian-luna-valero
    - JSKenyon
    - sjperkins
