{% set name = "dask-ms" %}
{% set version = "0.2.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 474f5fbe370e6422938a7ef8770215ef7dfa266a106da5b985bdc3e6f6323525

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core >=1.0
  run:
    - appdirs
    - donfig
    - python >=3.8
    - dask >=2023.1.0
    - numpy >=1.24.0
    - python-casacore >=3.5.1
    - s3fs >=2023.1.0
    - pyarrow >=12.0.0
    - zarr >=2.12.0
    - xarray >2023.1.0

test:
  imports:
    - daskms
  commands:
    - ${PYTHON} -c "from daskms import xds_from_ms"
    - ${PYTHON} -c "from daskms import xds_from_table"
    - ${PYTHON} -c "from daskms import xds_to_table"
    - ${PYTHON} -c "from daskms import TableProxy"

about:
  home: https://github.com/ska-sa/dask-ms
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Implementation of a dask/xarray dataset backed by a CASA MS

extra:
  recipe-maintainers:
    - sebastian-luna-valero
    - JSKenyon
    - sjperkins
